org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
kotlin.code.style=official
android.injected.testOnly=false
android.enableR8.fullMode=true
android.enableR8.rewriteArrayRuntimeChecks=true
android.enableR8.rewriteNullChecks=true
android.experimental.r8.kotlin-optimization=true
android.enableDexLayoutOptimizations=true
android.useNewNamespacingStrategy=false
kotlin.stdlib.default.dependency=false
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
